services:
  - type: .mp4
    name: https://kallietell.substack.com/p/pov-force-feeding-a-bully-until-shes
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    plan: free
